[package]
name = "jupiter-executor"
version = "0.1.0"
authors = ["Patract <https://github.com/patractlabs>"]
edition = "2018"

[dependencies]
frame-benchmarking = { git = "https://github.com/paritytech/substrate", branch = "master" }
sc-executor = { git = "https://github.com/paritytech/substrate", branch = "master" }

jupiter-io = { path = "../../../primitives/io" }

jupiter-runtime = { package = "jupiter-prep-runtime", path = "../../../runtime/jupiter-prep" }

[features]
wasmtime = [
  "sc-executor/wasmtime",
]
wasmi-errno = [
  "sc-executor/wasmi-errno",
]
