[package]
name = "jupiter-para-cli"
version = "0.1.0"
authors = ["Patract <https://github.com/patractlabs>"]
edition = "2018"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
futures = "0.3.4"
log = "0.4.8"
structopt = "0.3.8"
parking_lot = "0.11"
serde_json = "1.0"
hex-literal = "0.3.1"
codec = { package = 'parity-scale-codec', version = '2.1.0' }
ansi_term = "0.12.1"
serde = { version = "1.0.101", features = ["derive"] }

# Substrate dependencies
sc-authority-discovery = { version = "0.9.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.4"}
sc-basic-authorship = { version = "0.9.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.4"}
sc-transaction-pool = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.4"}
sc-network = { version = "0.9.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.4"}
sc-consensus = { version = "0.9.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.4"}
sc-finality-grandpa = { version = "0.9.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.4"}
sc-client-api = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.4"}
sc-rpc = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.4"}
sc-informant = { version = "0.9.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.4"}
sc-chain-spec = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.4"}
sc-telemetry = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.4" }

sp-core = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.4"}
sp-inherents = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.4"}
sp-transaction-pool = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.4"}
sp-consensus = { version = "0.9.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.4"}
sp-finality-grandpa = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.4"}
sp-runtime = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.4"}
sp-api = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.4"}
sc-cli = { version = "0.9.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.4", optional = true }
sc-service = { version = "0.9.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.4", optional = true }
sc-executor = { version = "0.9.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.4"}
frame-benchmarking = { version = "3.1.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.4"}
sp-session = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.4"}
sp-blockchain = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.4"}
sp-block-builder = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.4"}
sp-offchain = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.4"}
sp-timestamp = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.4"}
sc-tracing = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.4" }

pallet-contracts = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.4" }

# Cumulus dependencies
cumulus-client-cli = { git = "https://github.com/paritytech/cumulus", branch = "polkadot-v0.9.4"}
cumulus-client-consensus-relay-chain = { git = "https://github.com/paritytech/cumulus", branch = "polkadot-v0.9.4"}
cumulus-client-collator = { git = "https://github.com/paritytech/cumulus", branch = "polkadot-v0.9.4"}
cumulus-client-service = { git = "https://github.com/paritytech/cumulus", branch = "polkadot-v0.9.4"}
cumulus-client-network = { git = "https://github.com/paritytech/cumulus", branch = "polkadot-v0.9.4"}
cumulus-primitives-core = { git = "https://github.com/paritytech/cumulus", branch = "polkadot-v0.9.4"}
cumulus-primitives-parachain-inherent = { git = "https://github.com/paritytech/cumulus", branch = "polkadot-v0.9.4"}

# Polkadot dependencies
polkadot-primitives = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.4"}
polkadot-service = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.4"}
polkadot-cli = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.4"}
polkadot-parachain = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.4"}

# Jupiter
jupiter-io = { path = "../../../primitives/io" }
jupiter-primitives = { path = "../../../primitives" }
jupiter-rpc = { path = "../../../rpc" }
jupiter-runtime = { path = "../../../runtime/jupiter" }

[build-dependencies]
substrate-build-script-utils = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.4"}

[features]
default = ["cli"]
cli = [
  "sc-cli",
  "sc-service",
  "sc-executor/wasmi-errno",
]
wasmtime = [
  "sc-cli/wasmtime",
  "sc-service/wasmtime",
  "sc-executor/wasmtime",
]
