[package]
name = "jupiter-para-cli"
version = "0.1.0"
authors = ["Patract <https://github.com/patractlabs>"]
edition = "2018"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
futures = "0.3.4"
log = "0.4.8"
structopt = "0.3.8"
parking_lot = "0.10.0"
serde_json = "1.0"
hex-literal = "0.3.1"
codec = { package = 'parity-scale-codec', version = '2.0.0' }
ansi_term = "0.12.1"
serde = { version = "1.0.101", features = ["derive"] }

# Substrate dependencies
sc-authority-discovery = { git = "https://github.com/paritytech/substrate", branch = "master" }
sc-basic-authorship = { git = "https://github.com/paritytech/substrate", branch = "master" }
sc-transaction-pool = { git = "https://github.com/paritytech/substrate", branch = "master" }
sc-network = { git = "https://github.com/paritytech/substrate", branch = "master" }
sc-consensus-aura = { git = "https://github.com/paritytech/substrate", branch = "master" }
sc-consensus = { git = "https://github.com/paritytech/substrate", branch = "master" }
sc-finality-grandpa = { git = "https://github.com/paritytech/substrate", branch = "master" }
sc-client-api = { git = "https://github.com/paritytech/substrate", branch = "master" }
sc-rpc = { git = "https://github.com/paritytech/substrate", branch = "master" }
sc-informant = { git = "https://github.com/paritytech/substrate", branch = "master" }
sc-chain-spec = { git = "https://github.com/paritytech/substrate", branch = "master" }

sp-core = { git = "https://github.com/paritytech/substrate", branch = "master" }
sp-inherents = { git = "https://github.com/paritytech/substrate", branch = "master" }
sp-transaction-pool = { git = "https://github.com/paritytech/substrate", branch = "master" }
sp-consensus-aura = { git = "https://github.com/paritytech/substrate", branch = "master" }
sp-consensus = { git = "https://github.com/paritytech/substrate", branch = "master" }
sp-finality-grandpa = { git = "https://github.com/paritytech/substrate", branch = "master" }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "master" }
sp-api = { git = "https://github.com/paritytech/substrate", branch = "master" }
sc-cli = { git = "https://github.com/paritytech/substrate", branch = "master", optional = true }
sc-service = { git = "https://github.com/paritytech/substrate", branch = "master", optional = true }
sc-executor = { git = "https://github.com/paritytech/substrate", branch = "master" }
frame-benchmarking = { git = "https://github.com/paritytech/substrate", branch = "master" }
sp-session = { git = "https://github.com/paritytech/substrate", branch = "master" }
sp-blockchain = { git = "https://github.com/paritytech/substrate", branch = "master" }
sp-block-builder = { git = "https://github.com/paritytech/substrate", branch = "master" }
sp-offchain = { git = "https://github.com/paritytech/substrate", branch = "master" }
sp-timestamp = { git = "https://github.com/paritytech/substrate", branch = "master" }
sc-tracing = { git = "https://github.com/paritytech/substrate", branch = "master" }

pallet-contracts = { git = "https://github.com/paritytech/substrate", branch = "master" }

jupiter-primitives = { path = "../../../primitives" }
jupiter-rpc = { path = "../../../rpc" }

jupiter-para-runtime = { path = "../../../runtime/jupiter" }

# Cumulus dependencies
cumulus-consensus = { git = "https://github.com/paritytech/cumulus", branch = "master"}
cumulus-collator = { git = "https://github.com/paritytech/cumulus", branch = "master"}
cumulus-network = { git = "https://github.com/paritytech/cumulus", branch = "master"}
cumulus-primitives = { git = "https://github.com/paritytech/cumulus", branch = "master"}
cumulus-service = { git = "https://github.com/paritytech/cumulus", branch = "master"}

# Polkadot dependencies
polkadot-primitives = { git = "https://github.com/paritytech/polkadot", branch = "master"}
polkadot-service = { git = "https://github.com/paritytech/polkadot", branch = "master"}
polkadot-cli = { git = "https://github.com/paritytech/polkadot", branch = "master"}
polkadot-parachain = { git = "https://github.com/paritytech/polkadot", branch = "master"}

[build-dependencies]
substrate-build-script-utils = { git = "https://github.com/paritytech/substrate", branch = "master" }

[features]
default = ["cli"]
cli = [
  "sc-cli",
  "sc-service",
  "sc-executor/wasmi-errno",
]
wasmtime = [
  "sc-cli/wasmtime",
  "sc-service/wasmtime",
  "sc-executor/wasmtime",
]
